baseURL = "https://fernandoabolafio.github.io/dcrbounty"
title = "Decred Bug Bounty"
DefaultContentLanguage = "en"
copyright = "Decred Developers"
theme = "dcrbounty-theme"

[params.bannerLink]
  URL = "#Submit Vulnerability"

[languages]
  [languages.en]
    languageName = "english"
    contentDir = "content/en"
    weight = 10

  [languages.pt]
    languageName = "portuguÃªs"
    contentDir = "content/pt"
    weight = 30

# Nav links in the top bar
[[menu.main]]
name = "Hall of Fame"
url = "#hall_of_fame"
weight = 1

[[menu.main]]
name = "News and Updates"
url = "#news"
weight = 1

[[menu.main]]
name = "Rules"
url = "#Rules"
weight = 1

[[menu.main]]
name = "Submit Vulnerability"
url = "#Submit Vulnerability"
weight = 1